// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Bookmark               string
	BookmarkSearchConfig   string
	BookmarkSearchData     string
	BookmarkSearchDocsize  string
	BookmarkSearchIdx      string
	Creator                string
	File                   string
	FileSearchConfig       string
	FileSearchData         string
	FileSearchDocsize      string
	FileSearchIdx          string
	Publisher              string
	PublisherSearchConfig  string
	PublisherSearchData    string
	PublisherSearchDocsize string
	PublisherSearchIdx     string
	Subject                string
}{
	Bookmark:               "bookmark",
	BookmarkSearchConfig:   "bookmark_search_config",
	BookmarkSearchData:     "bookmark_search_data",
	BookmarkSearchDocsize:  "bookmark_search_docsize",
	BookmarkSearchIdx:      "bookmark_search_idx",
	Creator:                "creator",
	File:                   "file",
	FileSearchConfig:       "file_search_config",
	FileSearchData:         "file_search_data",
	FileSearchDocsize:      "file_search_docsize",
	FileSearchIdx:          "file_search_idx",
	Publisher:              "publisher",
	PublisherSearchConfig:  "publisher_search_config",
	PublisherSearchData:    "publisher_search_data",
	PublisherSearchDocsize: "publisher_search_docsize",
	PublisherSearchIdx:     "publisher_search_idx",
	Subject:                "subject",
}
