// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PublisherSearchDocsize is an object representing the database table.
type PublisherSearchDocsize struct {
	ID null.Int64 `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	SZ null.Bytes `boil:"sz" json:"sz,omitempty" toml:"sz" yaml:"sz,omitempty"`

	R *publisherSearchDocsizeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L publisherSearchDocsizeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PublisherSearchDocsizeColumns = struct {
	ID string
	SZ string
}{
	ID: "id",
	SZ: "sz",
}

var PublisherSearchDocsizeTableColumns = struct {
	ID string
	SZ string
}{
	ID: "publisher_search_docsize.id",
	SZ: "publisher_search_docsize.sz",
}

// Generated where

var PublisherSearchDocsizeWhere = struct {
	ID whereHelpernull_Int64
	SZ whereHelpernull_Bytes
}{
	ID: whereHelpernull_Int64{field: "\"publisher_search_docsize\".\"id\""},
	SZ: whereHelpernull_Bytes{field: "\"publisher_search_docsize\".\"sz\""},
}

// PublisherSearchDocsizeRels is where relationship names are stored.
var PublisherSearchDocsizeRels = struct {
}{}

// publisherSearchDocsizeR is where relationships are stored.
type publisherSearchDocsizeR struct {
}

// NewStruct creates a new relationship struct
func (*publisherSearchDocsizeR) NewStruct() *publisherSearchDocsizeR {
	return &publisherSearchDocsizeR{}
}

// publisherSearchDocsizeL is where Load methods for each relationship are stored.
type publisherSearchDocsizeL struct{}

var (
	publisherSearchDocsizeAllColumns            = []string{"id", "sz"}
	publisherSearchDocsizeColumnsWithoutDefault = []string{"sz"}
	publisherSearchDocsizeColumnsWithDefault    = []string{"id"}
	publisherSearchDocsizePrimaryKeyColumns     = []string{"id"}
	publisherSearchDocsizeGeneratedColumns      = []string{}
)

type (
	// PublisherSearchDocsizeSlice is an alias for a slice of pointers to PublisherSearchDocsize.
	// This should almost always be used instead of []PublisherSearchDocsize.
	PublisherSearchDocsizeSlice []*PublisherSearchDocsize
	// PublisherSearchDocsizeHook is the signature for custom PublisherSearchDocsize hook methods
	PublisherSearchDocsizeHook func(context.Context, boil.ContextExecutor, *PublisherSearchDocsize) error

	publisherSearchDocsizeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	publisherSearchDocsizeType                 = reflect.TypeOf(&PublisherSearchDocsize{})
	publisherSearchDocsizeMapping              = queries.MakeStructMapping(publisherSearchDocsizeType)
	publisherSearchDocsizePrimaryKeyMapping, _ = queries.BindMapping(publisherSearchDocsizeType, publisherSearchDocsizeMapping, publisherSearchDocsizePrimaryKeyColumns)
	publisherSearchDocsizeInsertCacheMut       sync.RWMutex
	publisherSearchDocsizeInsertCache          = make(map[string]insertCache)
	publisherSearchDocsizeUpdateCacheMut       sync.RWMutex
	publisherSearchDocsizeUpdateCache          = make(map[string]updateCache)
	publisherSearchDocsizeUpsertCacheMut       sync.RWMutex
	publisherSearchDocsizeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var publisherSearchDocsizeAfterSelectHooks []PublisherSearchDocsizeHook

var publisherSearchDocsizeBeforeInsertHooks []PublisherSearchDocsizeHook
var publisherSearchDocsizeAfterInsertHooks []PublisherSearchDocsizeHook

var publisherSearchDocsizeBeforeUpdateHooks []PublisherSearchDocsizeHook
var publisherSearchDocsizeAfterUpdateHooks []PublisherSearchDocsizeHook

var publisherSearchDocsizeBeforeDeleteHooks []PublisherSearchDocsizeHook
var publisherSearchDocsizeAfterDeleteHooks []PublisherSearchDocsizeHook

var publisherSearchDocsizeBeforeUpsertHooks []PublisherSearchDocsizeHook
var publisherSearchDocsizeAfterUpsertHooks []PublisherSearchDocsizeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PublisherSearchDocsize) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PublisherSearchDocsize) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PublisherSearchDocsize) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PublisherSearchDocsize) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PublisherSearchDocsize) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PublisherSearchDocsize) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PublisherSearchDocsize) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PublisherSearchDocsize) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PublisherSearchDocsize) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchDocsizeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPublisherSearchDocsizeHook registers your hook function for all future operations.
func AddPublisherSearchDocsizeHook(hookPoint boil.HookPoint, publisherSearchDocsizeHook PublisherSearchDocsizeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		publisherSearchDocsizeAfterSelectHooks = append(publisherSearchDocsizeAfterSelectHooks, publisherSearchDocsizeHook)
	case boil.BeforeInsertHook:
		publisherSearchDocsizeBeforeInsertHooks = append(publisherSearchDocsizeBeforeInsertHooks, publisherSearchDocsizeHook)
	case boil.AfterInsertHook:
		publisherSearchDocsizeAfterInsertHooks = append(publisherSearchDocsizeAfterInsertHooks, publisherSearchDocsizeHook)
	case boil.BeforeUpdateHook:
		publisherSearchDocsizeBeforeUpdateHooks = append(publisherSearchDocsizeBeforeUpdateHooks, publisherSearchDocsizeHook)
	case boil.AfterUpdateHook:
		publisherSearchDocsizeAfterUpdateHooks = append(publisherSearchDocsizeAfterUpdateHooks, publisherSearchDocsizeHook)
	case boil.BeforeDeleteHook:
		publisherSearchDocsizeBeforeDeleteHooks = append(publisherSearchDocsizeBeforeDeleteHooks, publisherSearchDocsizeHook)
	case boil.AfterDeleteHook:
		publisherSearchDocsizeAfterDeleteHooks = append(publisherSearchDocsizeAfterDeleteHooks, publisherSearchDocsizeHook)
	case boil.BeforeUpsertHook:
		publisherSearchDocsizeBeforeUpsertHooks = append(publisherSearchDocsizeBeforeUpsertHooks, publisherSearchDocsizeHook)
	case boil.AfterUpsertHook:
		publisherSearchDocsizeAfterUpsertHooks = append(publisherSearchDocsizeAfterUpsertHooks, publisherSearchDocsizeHook)
	}
}

// One returns a single publisherSearchDocsize record from the query.
func (q publisherSearchDocsizeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PublisherSearchDocsize, error) {
	o := &PublisherSearchDocsize{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for publisher_search_docsize")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PublisherSearchDocsize records from the query.
func (q publisherSearchDocsizeQuery) All(ctx context.Context, exec boil.ContextExecutor) (PublisherSearchDocsizeSlice, error) {
	var o []*PublisherSearchDocsize

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PublisherSearchDocsize slice")
	}

	if len(publisherSearchDocsizeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PublisherSearchDocsize records in the query.
func (q publisherSearchDocsizeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count publisher_search_docsize rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q publisherSearchDocsizeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if publisher_search_docsize exists")
	}

	return count > 0, nil
}

// PublisherSearchDocsizes retrieves all the records using an executor.
func PublisherSearchDocsizes(mods ...qm.QueryMod) publisherSearchDocsizeQuery {
	mods = append(mods, qm.From("\"publisher_search_docsize\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"publisher_search_docsize\".*"})
	}

	return publisherSearchDocsizeQuery{q}
}

// FindPublisherSearchDocsize retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPublisherSearchDocsize(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*PublisherSearchDocsize, error) {
	publisherSearchDocsizeObj := &PublisherSearchDocsize{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"publisher_search_docsize\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, publisherSearchDocsizeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from publisher_search_docsize")
	}

	if err = publisherSearchDocsizeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return publisherSearchDocsizeObj, err
	}

	return publisherSearchDocsizeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PublisherSearchDocsize) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no publisher_search_docsize provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(publisherSearchDocsizeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	publisherSearchDocsizeInsertCacheMut.RLock()
	cache, cached := publisherSearchDocsizeInsertCache[key]
	publisherSearchDocsizeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			publisherSearchDocsizeAllColumns,
			publisherSearchDocsizeColumnsWithDefault,
			publisherSearchDocsizeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(publisherSearchDocsizeType, publisherSearchDocsizeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(publisherSearchDocsizeType, publisherSearchDocsizeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"publisher_search_docsize\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"publisher_search_docsize\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into publisher_search_docsize")
	}

	if !cached {
		publisherSearchDocsizeInsertCacheMut.Lock()
		publisherSearchDocsizeInsertCache[key] = cache
		publisherSearchDocsizeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PublisherSearchDocsize.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PublisherSearchDocsize) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	publisherSearchDocsizeUpdateCacheMut.RLock()
	cache, cached := publisherSearchDocsizeUpdateCache[key]
	publisherSearchDocsizeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			publisherSearchDocsizeAllColumns,
			publisherSearchDocsizePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update publisher_search_docsize, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"publisher_search_docsize\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, publisherSearchDocsizePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(publisherSearchDocsizeType, publisherSearchDocsizeMapping, append(wl, publisherSearchDocsizePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update publisher_search_docsize row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for publisher_search_docsize")
	}

	if !cached {
		publisherSearchDocsizeUpdateCacheMut.Lock()
		publisherSearchDocsizeUpdateCache[key] = cache
		publisherSearchDocsizeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q publisherSearchDocsizeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for publisher_search_docsize")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for publisher_search_docsize")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PublisherSearchDocsizeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publisherSearchDocsizePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"publisher_search_docsize\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, publisherSearchDocsizePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in publisherSearchDocsize slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all publisherSearchDocsize")
	}
	return rowsAff, nil
}

// Delete deletes a single PublisherSearchDocsize record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PublisherSearchDocsize) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PublisherSearchDocsize provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), publisherSearchDocsizePrimaryKeyMapping)
	sql := "DELETE FROM \"publisher_search_docsize\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from publisher_search_docsize")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for publisher_search_docsize")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q publisherSearchDocsizeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no publisherSearchDocsizeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from publisher_search_docsize")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for publisher_search_docsize")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PublisherSearchDocsizeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(publisherSearchDocsizeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publisherSearchDocsizePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"publisher_search_docsize\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, publisherSearchDocsizePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from publisherSearchDocsize slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for publisher_search_docsize")
	}

	if len(publisherSearchDocsizeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PublisherSearchDocsize) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPublisherSearchDocsize(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PublisherSearchDocsizeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PublisherSearchDocsizeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publisherSearchDocsizePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"publisher_search_docsize\".* FROM \"publisher_search_docsize\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, publisherSearchDocsizePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PublisherSearchDocsizeSlice")
	}

	*o = slice

	return nil
}

// PublisherSearchDocsizeExists checks if the PublisherSearchDocsize row exists.
func PublisherSearchDocsizeExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"publisher_search_docsize\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if publisher_search_docsize exists")
	}

	return exists, nil
}

// Exists checks if the PublisherSearchDocsize row exists.
func (o *PublisherSearchDocsize) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PublisherSearchDocsizeExists(ctx, exec, o.ID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PublisherSearchDocsize) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no publisher_search_docsize provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(publisherSearchDocsizeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	publisherSearchDocsizeUpsertCacheMut.RLock()
	cache, cached := publisherSearchDocsizeUpsertCache[key]
	publisherSearchDocsizeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			publisherSearchDocsizeAllColumns,
			publisherSearchDocsizeColumnsWithDefault,
			publisherSearchDocsizeColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			publisherSearchDocsizeAllColumns,
			publisherSearchDocsizePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert publisher_search_docsize, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(publisherSearchDocsizePrimaryKeyColumns))
			copy(conflict, publisherSearchDocsizePrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"publisher_search_docsize\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(publisherSearchDocsizeType, publisherSearchDocsizeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(publisherSearchDocsizeType, publisherSearchDocsizeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert publisher_search_docsize")
	}

	if !cached {
		publisherSearchDocsizeUpsertCacheMut.Lock()
		publisherSearchDocsizeUpsertCache[key] = cache
		publisherSearchDocsizeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
