// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PublisherSearchConfig is an object representing the database table.
type PublisherSearchConfig struct {
	K string      `boil:"k" json:"k" toml:"k" yaml:"k"`
	V null.String `boil:"v" json:"v,omitempty" toml:"v" yaml:"v,omitempty"`

	R *publisherSearchConfigR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L publisherSearchConfigL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PublisherSearchConfigColumns = struct {
	K string
	V string
}{
	K: "k",
	V: "v",
}

var PublisherSearchConfigTableColumns = struct {
	K string
	V string
}{
	K: "publisher_search_config.k",
	V: "publisher_search_config.v",
}

// Generated where

var PublisherSearchConfigWhere = struct {
	K whereHelperstring
	V whereHelpernull_String
}{
	K: whereHelperstring{field: "\"publisher_search_config\".\"k\""},
	V: whereHelpernull_String{field: "\"publisher_search_config\".\"v\""},
}

// PublisherSearchConfigRels is where relationship names are stored.
var PublisherSearchConfigRels = struct {
}{}

// publisherSearchConfigR is where relationships are stored.
type publisherSearchConfigR struct {
}

// NewStruct creates a new relationship struct
func (*publisherSearchConfigR) NewStruct() *publisherSearchConfigR {
	return &publisherSearchConfigR{}
}

// publisherSearchConfigL is where Load methods for each relationship are stored.
type publisherSearchConfigL struct{}

var (
	publisherSearchConfigAllColumns            = []string{"k", "v"}
	publisherSearchConfigColumnsWithoutDefault = []string{"k", "v"}
	publisherSearchConfigColumnsWithDefault    = []string{}
	publisherSearchConfigPrimaryKeyColumns     = []string{"k"}
	publisherSearchConfigGeneratedColumns      = []string{}
)

type (
	// PublisherSearchConfigSlice is an alias for a slice of pointers to PublisherSearchConfig.
	// This should almost always be used instead of []PublisherSearchConfig.
	PublisherSearchConfigSlice []*PublisherSearchConfig
	// PublisherSearchConfigHook is the signature for custom PublisherSearchConfig hook methods
	PublisherSearchConfigHook func(context.Context, boil.ContextExecutor, *PublisherSearchConfig) error

	publisherSearchConfigQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	publisherSearchConfigType                 = reflect.TypeOf(&PublisherSearchConfig{})
	publisherSearchConfigMapping              = queries.MakeStructMapping(publisherSearchConfigType)
	publisherSearchConfigPrimaryKeyMapping, _ = queries.BindMapping(publisherSearchConfigType, publisherSearchConfigMapping, publisherSearchConfigPrimaryKeyColumns)
	publisherSearchConfigInsertCacheMut       sync.RWMutex
	publisherSearchConfigInsertCache          = make(map[string]insertCache)
	publisherSearchConfigUpdateCacheMut       sync.RWMutex
	publisherSearchConfigUpdateCache          = make(map[string]updateCache)
	publisherSearchConfigUpsertCacheMut       sync.RWMutex
	publisherSearchConfigUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var publisherSearchConfigAfterSelectHooks []PublisherSearchConfigHook

var publisherSearchConfigBeforeInsertHooks []PublisherSearchConfigHook
var publisherSearchConfigAfterInsertHooks []PublisherSearchConfigHook

var publisherSearchConfigBeforeUpdateHooks []PublisherSearchConfigHook
var publisherSearchConfigAfterUpdateHooks []PublisherSearchConfigHook

var publisherSearchConfigBeforeDeleteHooks []PublisherSearchConfigHook
var publisherSearchConfigAfterDeleteHooks []PublisherSearchConfigHook

var publisherSearchConfigBeforeUpsertHooks []PublisherSearchConfigHook
var publisherSearchConfigAfterUpsertHooks []PublisherSearchConfigHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PublisherSearchConfig) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PublisherSearchConfig) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PublisherSearchConfig) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PublisherSearchConfig) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PublisherSearchConfig) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PublisherSearchConfig) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PublisherSearchConfig) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PublisherSearchConfig) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PublisherSearchConfig) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range publisherSearchConfigAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPublisherSearchConfigHook registers your hook function for all future operations.
func AddPublisherSearchConfigHook(hookPoint boil.HookPoint, publisherSearchConfigHook PublisherSearchConfigHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		publisherSearchConfigAfterSelectHooks = append(publisherSearchConfigAfterSelectHooks, publisherSearchConfigHook)
	case boil.BeforeInsertHook:
		publisherSearchConfigBeforeInsertHooks = append(publisherSearchConfigBeforeInsertHooks, publisherSearchConfigHook)
	case boil.AfterInsertHook:
		publisherSearchConfigAfterInsertHooks = append(publisherSearchConfigAfterInsertHooks, publisherSearchConfigHook)
	case boil.BeforeUpdateHook:
		publisherSearchConfigBeforeUpdateHooks = append(publisherSearchConfigBeforeUpdateHooks, publisherSearchConfigHook)
	case boil.AfterUpdateHook:
		publisherSearchConfigAfterUpdateHooks = append(publisherSearchConfigAfterUpdateHooks, publisherSearchConfigHook)
	case boil.BeforeDeleteHook:
		publisherSearchConfigBeforeDeleteHooks = append(publisherSearchConfigBeforeDeleteHooks, publisherSearchConfigHook)
	case boil.AfterDeleteHook:
		publisherSearchConfigAfterDeleteHooks = append(publisherSearchConfigAfterDeleteHooks, publisherSearchConfigHook)
	case boil.BeforeUpsertHook:
		publisherSearchConfigBeforeUpsertHooks = append(publisherSearchConfigBeforeUpsertHooks, publisherSearchConfigHook)
	case boil.AfterUpsertHook:
		publisherSearchConfigAfterUpsertHooks = append(publisherSearchConfigAfterUpsertHooks, publisherSearchConfigHook)
	}
}

// One returns a single publisherSearchConfig record from the query.
func (q publisherSearchConfigQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PublisherSearchConfig, error) {
	o := &PublisherSearchConfig{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for publisher_search_config")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PublisherSearchConfig records from the query.
func (q publisherSearchConfigQuery) All(ctx context.Context, exec boil.ContextExecutor) (PublisherSearchConfigSlice, error) {
	var o []*PublisherSearchConfig

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PublisherSearchConfig slice")
	}

	if len(publisherSearchConfigAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PublisherSearchConfig records in the query.
func (q publisherSearchConfigQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count publisher_search_config rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q publisherSearchConfigQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if publisher_search_config exists")
	}

	return count > 0, nil
}

// PublisherSearchConfigs retrieves all the records using an executor.
func PublisherSearchConfigs(mods ...qm.QueryMod) publisherSearchConfigQuery {
	mods = append(mods, qm.From("\"publisher_search_config\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"publisher_search_config\".*"})
	}

	return publisherSearchConfigQuery{q}
}

// FindPublisherSearchConfig retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPublisherSearchConfig(ctx context.Context, exec boil.ContextExecutor, k string, selectCols ...string) (*PublisherSearchConfig, error) {
	publisherSearchConfigObj := &PublisherSearchConfig{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"publisher_search_config\" where \"k\"=?", sel,
	)

	q := queries.Raw(query, k)

	err := q.Bind(ctx, exec, publisherSearchConfigObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from publisher_search_config")
	}

	if err = publisherSearchConfigObj.doAfterSelectHooks(ctx, exec); err != nil {
		return publisherSearchConfigObj, err
	}

	return publisherSearchConfigObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PublisherSearchConfig) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no publisher_search_config provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(publisherSearchConfigColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	publisherSearchConfigInsertCacheMut.RLock()
	cache, cached := publisherSearchConfigInsertCache[key]
	publisherSearchConfigInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			publisherSearchConfigAllColumns,
			publisherSearchConfigColumnsWithDefault,
			publisherSearchConfigColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(publisherSearchConfigType, publisherSearchConfigMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(publisherSearchConfigType, publisherSearchConfigMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"publisher_search_config\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"publisher_search_config\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into publisher_search_config")
	}

	if !cached {
		publisherSearchConfigInsertCacheMut.Lock()
		publisherSearchConfigInsertCache[key] = cache
		publisherSearchConfigInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PublisherSearchConfig.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PublisherSearchConfig) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	publisherSearchConfigUpdateCacheMut.RLock()
	cache, cached := publisherSearchConfigUpdateCache[key]
	publisherSearchConfigUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			publisherSearchConfigAllColumns,
			publisherSearchConfigPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update publisher_search_config, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"publisher_search_config\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, publisherSearchConfigPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(publisherSearchConfigType, publisherSearchConfigMapping, append(wl, publisherSearchConfigPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update publisher_search_config row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for publisher_search_config")
	}

	if !cached {
		publisherSearchConfigUpdateCacheMut.Lock()
		publisherSearchConfigUpdateCache[key] = cache
		publisherSearchConfigUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q publisherSearchConfigQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for publisher_search_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for publisher_search_config")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PublisherSearchConfigSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publisherSearchConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"publisher_search_config\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, publisherSearchConfigPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in publisherSearchConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all publisherSearchConfig")
	}
	return rowsAff, nil
}

// Delete deletes a single PublisherSearchConfig record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PublisherSearchConfig) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PublisherSearchConfig provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), publisherSearchConfigPrimaryKeyMapping)
	sql := "DELETE FROM \"publisher_search_config\" WHERE \"k\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from publisher_search_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for publisher_search_config")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q publisherSearchConfigQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no publisherSearchConfigQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from publisher_search_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for publisher_search_config")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PublisherSearchConfigSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(publisherSearchConfigBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publisherSearchConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"publisher_search_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, publisherSearchConfigPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from publisherSearchConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for publisher_search_config")
	}

	if len(publisherSearchConfigAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PublisherSearchConfig) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPublisherSearchConfig(ctx, exec, o.K)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PublisherSearchConfigSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PublisherSearchConfigSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), publisherSearchConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"publisher_search_config\".* FROM \"publisher_search_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, publisherSearchConfigPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PublisherSearchConfigSlice")
	}

	*o = slice

	return nil
}

// PublisherSearchConfigExists checks if the PublisherSearchConfig row exists.
func PublisherSearchConfigExists(ctx context.Context, exec boil.ContextExecutor, k string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"publisher_search_config\" where \"k\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, k)
	}
	row := exec.QueryRowContext(ctx, sql, k)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if publisher_search_config exists")
	}

	return exists, nil
}

// Exists checks if the PublisherSearchConfig row exists.
func (o *PublisherSearchConfig) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PublisherSearchConfigExists(ctx, exec, o.K)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PublisherSearchConfig) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no publisher_search_config provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(publisherSearchConfigColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	publisherSearchConfigUpsertCacheMut.RLock()
	cache, cached := publisherSearchConfigUpsertCache[key]
	publisherSearchConfigUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			publisherSearchConfigAllColumns,
			publisherSearchConfigColumnsWithDefault,
			publisherSearchConfigColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			publisherSearchConfigAllColumns,
			publisherSearchConfigPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert publisher_search_config, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(publisherSearchConfigPrimaryKeyColumns))
			copy(conflict, publisherSearchConfigPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"publisher_search_config\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(publisherSearchConfigType, publisherSearchConfigMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(publisherSearchConfigType, publisherSearchConfigMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert publisher_search_config")
	}

	if !cached {
		publisherSearchConfigUpsertCacheMut.Lock()
		publisherSearchConfigUpsertCache[key] = cache
		publisherSearchConfigUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
